### ISSUE TITLE
Running tests in node environment

### ISSUE THREAD

**Issue by tvthatsme** [hustcc/jest-canvas-mock#6]
I have `jest-canvas-mock` configured in my package.json:
```
"jest": {
  "setupFiles": [
    "jest-canvas-mock"
  ]
}
```

This is working great for my tests 🎉 

However, I'm running some new tests in the [node test environment](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string) by using the docblock at the top of the file. In this case `jest-canvas-mock` is throwing an error that window is not defined (which is expected I guess)

Is there any way that the canvas mock can be disabled for jest test files that are run in the node environment?

**Comment by hustcc** [comment]
Can show me the throwing error? And how are you running canvas on nodejs?

**Comment by tvthatsme** [comment]
The error I am getting is this:
```
ReferenceError: window is not defined
at Object.<anonymous> (node_modules/jest-canvas-mock/lib/index.js:10:39)
```

I'm testing a React component that depends on Canvas, but testing with Jest and jsdom needs to have Canvas mocked so I used your package.

However, the component can be rendered on the client or server-side. Because I've mocked Canvas with this package though, my server-side (node) environment tests don't work because of the above message.

**Comment by hustcc** [comment]
jest-canvas-mock is used to mock canvas in `test` env with jest. Use it in dev / prod env is not recommended.

I do not whether  we can do something on jest-canvas-mock to mock canvas when ssr. Maybe you can hava a try and send a pr.

**Comment by tvthatsme** [comment]
What I'm asking is this: 

Jest allows for testing in different environments (jsdom or node). I'm using jest-canvas-mock for the jsdom environment. But can I turn of jest-canvas-mock when Jest is running in the node environment? Is that even possible do you think?

I did some digging and it seems like I can get the desired result with this modification to index.js, basically wrapping the global assignment in an check if window is even defined.
```
if (typeof window !== 'undefined') {
  global.window = (0, _window2.default)(window)
}
```

What would you think of a PR like that?

**Comment by hustcc** [comment]
Why you run jest in `node` env when canvas has been used?

**Comment by hustcc** [comment]
v1.0.3 released.

**Comment by icd2k3** [comment]
@hustcc & @tvthatsme to add some context we have a large test suite. Some tests use jsdom, but others use node.

In our config we have `testEnvironment: jsdom` for the overall default. However, for module tests that _don't_ need jsdom we add: `@jest-environment node` to the top of each test described here: https://jestjs.io/docs/en/configuration#testenvironment-string

This is because using the node environment where possible is slightly more performant. The problem is that since `jest-canvas-mock` is used in the setup file it runs for _every_ test.

What I've been doing is `import 'jest-canvas-mock';` in _individual_ tests that use canvas. This seems to work fine!
